[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "aprl"
dynamic = ['version']
dependencies = ["hydra-zen"]


[project.optional-dependencies]
experimental = ["toolz"]
all = ["aprl[experimental]"]
